# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171119_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='contra_m',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='denuncia_m',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='favor_m',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rango_m',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reportados_m',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
