# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171120_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contra_m',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='denuncia_m',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='favor_m',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rango_m',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reportados_m',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
